#!/usr/bin/env bash

# Get / Set Variables
if [ -n "$1" ]; then
  URL=$1
else
  URL=`cat ~/.zsync-default-url | tr -d '\n'`
fi

ZSYNCFILENAME=${URL##*/}
OUTPUTFILENAME=${ZSYNCFILENAME%\.zsync}
ZSYNCSDIR=~/.zsyncs/
ZSYNCFILEWITHFULLPATH="$ZSYNCSDIR$ZSYNCFILENAME"

#ZSYNCFILENAME=$2
#OUTPUTFILENAME=$3

# Fetch the new Zsync file (if it was updated at the server) and record if it changed
MODDATE1=`stat -c %y ~/.zsyncs/$ZSYNCFILENAME`

if test -e "$ZSYNCFILEWITHFULLPATH"
then zflag="-z $ZSYNCFILEWITHFULLPATH"
else zflag=
fi
curl -o "$ZSYNCFILEWITHFULLPATH" $zflag "$URL"

MODDATE2=`stat -c %y ~/.zsyncs/$ZSYNCFILENAME`

# DEBUGGING
if [ $DEBUGGING ]; then
  echo "echoing filename from url"
  echo "${URL##*/}"
  echo

  echo "echoing extracted substring (payload file from \"file.zsync\" filename)"
  echo ${ZSYNCFILENAME%\.zsync}
  echo

  echo "echoing \$1"
  echo $1

  echo "echoing \$URL"
  echo $URL
  echo

  echo "echoing \$2"
  echo $2

  echo "echoing \$ZSYNCFILENAME"
  echo $ZSYNCFILENAME
  echo

  echo "echoing \$3"
  echo $3

  echo "echoing \$OUTPUTFILENAME"
  echo $OUTPUTFILENAME
  echo

  echo "echoing \$MODDATE1"
  echo $MODDATE1

  echo "echoing \$MODDATE2"
  echo $MODDATE2
  echo
fi
# /DEBUGGING

if [ "$MODDATE1" != "$MODDATE2" ]; then
  # Run the "payload" zsync command for this script
    zsync $URL -k ~/.zsyncs/$ZSYNCFILENAME -i ~/Downloads/$OUTPUTFILENAME -o ~/Downloads/$OUTPUTFILENAME
else
  # Nothing to do!
  echo "Zsync file already up-to-date. Nothing to update or download."
fi
